// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_bazy.Data;

#nullable disable

namespace Projekt_bazy.Migrations
{
    [DbContext(typeof(MagazynDbContext))]
    [Migration("20250115132849_updatezama")]
    partial class updatezama
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt_bazy.Models.Magazyn", b =>
                {
                    b.Property<int>("IdMagazynu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMagazynu"));

                    b.Property<string>("Funkcjonalnosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMagazynu");

                    b.ToTable("Magazyny");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Personel", b =>
                {
                    b.Property<int>("IdPersonelu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonelu"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Przynaleznosc")
                        .HasColumnType("int");

                    b.Property<string>("Stopien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersonelu");

                    b.HasIndex("Przynaleznosc");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Sprzet", b =>
                {
                    b.Property<int>("IdSprzetu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSprzetu"));

                    b.Property<DateTime>("DataWstawienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<string>("NazwaSprzetu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSprzetu");

                    b.HasIndex("MagazynId");

                    b.ToTable("Sprzety");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Zamowienia", b =>
                {
                    b.Property<int>("IdZamowienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZamowienia"));

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<int?>("MagazynIdMagazynu")
                        .HasColumnType("int");

                    b.Property<string>("NazwaSprzetu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZamawiajacyId")
                        .HasColumnType("int");

                    b.HasKey("IdZamowienia");

                    b.HasIndex("MagazynId");

                    b.HasIndex("MagazynIdMagazynu");

                    b.HasIndex("ZamawiajacyId");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Personel", b =>
                {
                    b.HasOne("Projekt_bazy.Models.Magazyn", "Magazyn")
                        .WithMany("Personel")
                        .HasForeignKey("Przynaleznosc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Sprzet", b =>
                {
                    b.HasOne("Projekt_bazy.Models.Magazyn", "Magazyn")
                        .WithMany("Sprzety")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Zamowienia", b =>
                {
                    b.HasOne("Projekt_bazy.Models.Magazyn", "Magazyn")
                        .WithMany()
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projekt_bazy.Models.Magazyn", null)
                        .WithMany("Zamowienia")
                        .HasForeignKey("MagazynIdMagazynu");

                    b.HasOne("Projekt_bazy.Models.Personel", "Zamawiajacy")
                        .WithMany("Zamowienia")
                        .HasForeignKey("ZamawiajacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Magazyn");

                    b.Navigation("Zamawiajacy");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Magazyn", b =>
                {
                    b.Navigation("Personel");

                    b.Navigation("Sprzety");

                    b.Navigation("Zamowienia");
                });

            modelBuilder.Entity("Projekt_bazy.Models.Personel", b =>
                {
                    b.Navigation("Zamowienia");
                });
#pragma warning restore 612, 618
        }
    }
}
